# -*- coding: utf-8 -*-
"""Task(python.Dictionaries.)ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZoZcMY2ZaB3pGQ4yDgXAcHe_ulqAWhC

\1) Write a program to merge two dictionaries into one. If there are overlapping keys, sum their values.

2) Write a Python program to create an empty dictionary.

3) Write a Python script to iterate over a dictionary and print all key-value pairs.

4) Write a Python program to remove the key-value pair with key 'age' from  dictionary

5) Write a program to sort a dictionary by its keys in ascending order and print the sorted dictionary.

6) Given a dictionary students_scores = {'Alice': 85, 'Bob': 90}, update the score for 'Alice' to 95. If 'Charlie' does not exist in the dictionary, add 'Charlie' with a default score of 60.

7) Write a Python program to print all the values in  dictionary:

8) Given a dictionary item_prices = {'apple': 1.00, 'banana': 0.50}, calculate the total price of all items. Then, apply a 10% discount to all items and update the dictionary.
"""

# Sual 1:
dict1={"Julia":70,"Tesla":80,"Nict":59}
dict2={"Julia":60,"Tesla":90,"Tornd":75}
for i in dict1.keys():
  for j in dict2.keys():
    if i==j:
      print(dict1[i]+dict2[j])

# Sual 2:
dictinory={}
print(dictinory)

# Sual 3:
dicts={"Name" : "Julia", "Surname" : "Tesla","age" : 25}
print(dicts.items())

# Sual 4:
dicts={"Name" : "Julia", "Surname" : "Tesla","Age" : 25}
dicts.pop("Age")
print(dicts)

# Sual 5:
dicts={"Name" : "Julia", "Surname" : "Tesla","Age" : 25 }
dict2=sorted(dicts.keys())
print(dict2)

# Sual 6:
student_scores = {'Alisa': 85, 'Bob': 90}
student_scores.update({'Alisa': 95})
student_scores.setdefault("Carli", 60)
print(student_scores)

# Sual 7:
dicts={"Name" : "Julia", "Surname" : "Tesla","Age" : 25 }
print(dicts.values())

item_prices = {'apple': 1.00, 'banana': 0.50,'chery' : 2.00}
print(sum(item_prices.values()))
for i in item_prices:
  item_prices[i]*=1.1
print(item_prices)